import NextAuth from "next-auth";
import Keycloak from "next-auth/providers/keycloak";
import { keycloakOptions } from "@/lib/auth/keycloakOptions";
import { sidFromIdToken } from "@/lib/auth/sessionId";
import { createdSession } from "@/lib/auth/signInContext";
import { putSessionAccount, putSessionSid, valkeyAdapter } from "@/lib/auth/valkeyAdapter";

export const { handlers, auth, signIn, signOut } = NextAuth({
  adapter: valkeyAdapter,
  // Mirrors the realm's ssoSessionMaxLifespan. Do not raise maxAge above
  // updateAge expecting a sliding session: Auth.js only re-dates once
  // `expires - maxAge + updateAge` has passed (@auth/core's
  // lib/actions/session.js) — equal values mean a fixed 10h expiry, the intent.
  session: { strategy: "database", maxAge: 10 * 60 * 60, updateAge: 10 * 60 * 60 },
  // Required when self-hosting off Vercel: without it, Auth.js rejects
  // every request's Host header as untrusted (errors.authjs.dev#untrustedhost).
  trustHost: true,
  providers: [
    Keycloak(keycloakOptions),
    {
      // A second, distinct provider rather than a parameter on "keycloak":
      // signIn() picks the provider whose id it's given, and Auth.js has no
      // per-call override for which endpoint the redirect targets. Explicitly
      // setting `authorization.url` here only replaces the redirect target —
      // state, PKCE and nonce are still generated by Auth.js itself
      // (@auth/core's authorization-url.js), and the token/userinfo/jwks
      // endpoints are still the ones `issuer` discovers, same as "keycloak".
      // ADR-0025's hand-rolled-OIDC concern does not apply: nothing here
      // bypasses Auth.js's own request construction or callback validation.
      ...Keycloak(keycloakOptions),
      id: "keycloak-register",
      name: "Keycloak (register)",
      authorization: {
        url: `${process.env.AUTH_KEYCLOAK_ISSUER}/protocol/openid-connect/registrations`,
      },
    },
  ],
  events: {
    // Do not remove: the only point Auth.js hands the provider's token set
    // to the application, since the Adapter interface has no updateAccount.
    // Nothing fails loudly without it — sign-in still succeeds but reaches
    // no protected endpoint later.
    signIn: async ({ user, account }) => {
      // "credentials" is the one provider type the Adapter's account model
      // does not cover; this app has no such provider, so it cannot occur.
      if (!account || !user.id || account.type === "credentials") {
        return;
      }
      const session = createdSession();
      // No session means Auth.js reused an existing one; its tokens stay
      // current via lazy renewal instead (lib/api/accessToken.ts, ADR-0029).
      if (!session) {
        return;
      }
      await putSessionAccount(
        session.sessionToken,
        { ...account, type: account.type, userId: user.id },
        session.expires,
      );
      // Indexes by Keycloak sid so Back-Channel Logout can find the session (ADR-0031).
      const sid = account.id_token ? sidFromIdToken(account.id_token) : undefined;
      if (sid) {
        await putSessionSid(session.sessionToken, sid, session.expires);
      }
    },
  },
});
